### ISSUE TITLE
bpemb model download fails

### ISSUE THREAD

**Issue by valentinschabschneider** [GRAAL-Research/deepparse#232] opened 2024-07-08 14:04 UTC
**Describe the bug**

When using the new ghcr.io/graal-research/deepparse:0.9.10 docker image (after fixing #231) the following error occurs:

```
app-1  | 2024-07-08 13:56:01,032; DEBUG: Starting new HTTPS connection (1): bpemb.h-its.org:443
app-1  | 2024-07-08 13:56:01,126; DEBUG: https://bpemb.h-its.org:443 "GET /multi/multi.wiki.bpe.vs100000.model HTTP/11" 404 196
app-1  | ERROR:    Traceback (most recent call last):
app-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
app-1  |     async with self.lifespan_context(app) as maybe_state:
app-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
app-1  |     return await anext(self.gen)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/deepparse/app/app.py", line 31, in lifespan
app-1  |     download_models()
app-1  |   File "/deepparse/download_tools.py", line 106, in download_models
app-1  |     download_model(model_type, saving_cache_path=saving_cache_path)
app-1  |   File "/deepparse/download_tools.py", line 130, in download_model
app-1  |     BPEmb(
app-1  |   File "/usr/local/lib/python3.11/site-packages/bpemb/bpemb.py", line 173, in __init__
app-1  |     self.model_file = self._load_file(model_file)
app-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/bpemb/bpemb.py", line 228, in _load_file
app-1  |     return http_get(file_url, cached_file, ignore_tardir=True)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/bpemb/util.py", line 48, in http_get
app-1  |     headers = http_get_temp(url, temp_file)
app-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/usr/local/lib/python3.11/site-packages/bpemb/util.py", line 25, in http_get_temp
app-1  |     req.raise_for_status()
app-1  |   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
app-1  |     raise HTTPError(http_error_msg, response=self)
app-1  | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://bpemb.h-its.org/multi/multi.wiki.bpe.vs100000.model
app-1  |
app-1  | ERROR:    Application startup failed. Exiting.
app-1 exited with code 3
```

**To Reproduce**
Run the provided docker-compose.yml with the ghcr.io/graal-research/deepparse:0.9.10 image.

**Expected behavior**
The model is downloaded container starts normally.

**Desktop (please complete the following information):**
 - Docker
 - Version 0.9.10

**Comment by valentinschabschneider** [comment] 2024-07-08 14:05
I saw that this was attempted to be fixed but it still doesnt point to the correct path `https://bpemb.h-its.org/multi/multi/multi.wiki.bpe.vs100000.model`

**Comment by davebulaval** [comment] 2024-07-09 02:47
It was fixed; the docker image seems to be the wrong one. It is fixed with 0.9.11.

**Closed by davebulaval** 2024-07-09 02:47 UTC
Labels: bug

**Comment by valentinschabschneider** [comment] 2024-07-09 06:24
unfortunately the error still occurs

**Comment by valentinschabschneider** [comment] 2024-07-09 06:35
The fix applied in [bpemb_embeddings_model.py](https://github.com/GRAAL-Research/deepparse/blob/main/deepparse/embeddings_models/bpemb_embeddings_model.py) with `BPEmbBaseURLWrapperBugFix` needs also be applied in [download_tools.py#L130](https://github.com/GRAAL-Research/deepparse/blob/main/deepparse/download_tools.py#L130)

**Comment by davebulaval** [comment] 2024-07-09 13:03
You are right. It is fixed in 0.9.12.

**Comment by MAYAS3** [comment] 2025-07-09 15:57
Hello @deliqs,

There seems to be an  issue with our hosting server. We are looking into it.

In the mean time, have you ever used Deepparse outside of this container? If so, the model checkpoints should be in your `.cache/deepparse` directory.

I'll let you know when the issue is fixed.

Sorry for the inconvenience!

**Comment by jerry1399585** [comment] 2025-07-23 12:25
not able to download the model file of bpemb ....ckpt got error http 404 not found

**Comment by MAYAS3** [comment] 2025-07-23 12:36
Hello @jerry1399585,

As mentioned above, we've been having problems with our storage solution, so we decided to move to a different infrastructure.

The new integration is functional, I'm just finalizing some tests and should publish a new version this week.

Again, sorry everyone !

**Comment by movien** [comment] 2025-07-24 16:56
> [@deliqs](https://github.com/deliqs) [@jerry1399585](https://github.com/jerry1399585) version `0.9.14` is released and should fix the above issues.
> 
> You can update the package by running `pip install -U deepparse`
> 
> Please let me know if you encounter any further issues.

I'm a new to deepparse ... kind of getting same error as before. Unable to download pre-trained weights for the network bpemb.

**Comment by MAYAS3** [comment] 2025-07-24 16:59
@movien Did you make sure you are running the latest version (0.9.14)?

If so, please share the error output you're getting so I can take a look.

**Comment by movien** [comment] 2025-07-24 17:08
> [@movien](https://github.com/movien) Did you make sure you are running the latest version (0.9.14)?
> 
> If so, please share the error output you're getting so I can take a look.

Sorry, looks good with 0.9.14. Earlier tested version was 0.9.13 which has that error. Thanks a lot! :)
